-- MySQL Script generated by MySQL Workbench
-- Tue Nov  7 19:10:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`sport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sport` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sport` (
  `id` INT NOT NULL,
  `sport` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`znacka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`znacka` ;

CREATE TABLE IF NOT EXISTS `mydb`.`znacka` (
  `id` INT NOT NULL,
  `znacka` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`typ_produktu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`typ_produktu` ;

CREATE TABLE IF NOT EXISTS `mydb`.`typ_produktu` (
  `id` INT NOT NULL,
  `typ_produktu` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produkt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`produkt` ;

CREATE TABLE IF NOT EXISTS `mydb`.`produkt` (
  `id` INT NOT NULL,
  `nazev` VARCHAR(45) NULL,
  `popis` VARCHAR(45) NULL,
  `cena` INT NULL,
  `id_sportu` INT NOT NULL,
  `id_znacky` INT NOT NULL,
  `hodnoceni_produktu` FLOAT NULL,
  `cena_ve_sleve` INT NULL,
  `typ_produktu_id` INT NOT NULL,
  PRIMARY KEY (`id`, `id_sportu`, `id_znacky`, `typ_produktu_id`),
  INDEX `fk_produkt_sport1_idx` (`id_sportu` ASC) VISIBLE,
  INDEX `fk_produkt_znacka1_idx` (`id_znacky` ASC) VISIBLE,
  INDEX `fk_produkt_typ_produktu1_idx` (`typ_produktu_id` ASC) VISIBLE,
  CONSTRAINT `fk_produkt_sport1`
    FOREIGN KEY (`id_sportu`)
    REFERENCES `mydb`.`sport` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produkt_znacka1`
    FOREIGN KEY (`id_znacky`)
    REFERENCES `mydb`.`znacka` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produkt_typ_produktu1`
    FOREIGN KEY (`typ_produktu_id`)
    REFERENCES `mydb`.`typ_produktu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`uzivatel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`uzivatel` ;

CREATE TABLE IF NOT EXISTS `mydb`.`uzivatel` (
  `id` INT NOT NULL,
  `heslo` VARCHAR(45) NULL,
  `prijmeni` VARCHAR(45) NULL,
  `jmeno` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefonni_cislo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recenze`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`recenze` ;

CREATE TABLE IF NOT EXISTS `mydb`.`recenze` (
  `id` INT NOT NULL,
  `recenze` VARCHAR(45) NULL,
  `id_uzivatele` INT NOT NULL,
  `pocet_hvezd` INT NULL,
  `id_produktu` INT NOT NULL,
  PRIMARY KEY (`id`, `id_uzivatele`, `id_produktu`),
  INDEX `fk_recenze_uzivatel1_idx` (`id_uzivatele` ASC) VISIBLE,
  INDEX `fk_recenze_produkt1_idx` (`id_produktu` ASC) VISIBLE,
  CONSTRAINT `fk_recenze_uzivatel1`
    FOREIGN KEY (`id_uzivatele`)
    REFERENCES `mydb`.`uzivatel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recenze_produkt1`
    FOREIGN KEY (`id_produktu`)
    REFERENCES `mydb`.`produkt` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`slevovy kod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`slevovy kod` ;

CREATE TABLE IF NOT EXISTS `mydb`.`slevovy kod` (
  `id` INT NOT NULL,
  `slevovy_kod` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`barva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`barva` ;

CREATE TABLE IF NOT EXISTS `mydb`.`barva` (
  `id` INT NOT NULL,
  `barva` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`velikost`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`velikost` ;

CREATE TABLE IF NOT EXISTS `mydb`.`velikost` (
  `id` INT NOT NULL,
  `velikost` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`obrazek`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`obrazek` ;

CREATE TABLE IF NOT EXISTS `mydb`.`obrazek` (
  `id` INT NOT NULL,
  `cesta_k_obrazku` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`slevovy_kod_na_sporty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`slevovy_kod_na_sporty` ;

CREATE TABLE IF NOT EXISTS `mydb`.`slevovy_kod_na_sporty` (
  `id_sportu` INT NOT NULL,
  `id_slevoveho_kodu` INT NOT NULL,
  PRIMARY KEY (`id_sportu`, `id_slevoveho_kodu`),
  INDEX `fk_sport_has_slevovy kod_slevovy kod1_idx` (`id_slevoveho_kodu` ASC) VISIBLE,
  INDEX `fk_sport_has_slevovy kod_sport1_idx` (`id_sportu` ASC) VISIBLE,
  CONSTRAINT `fk_sport_has_slevovy kod_sport1`
    FOREIGN KEY (`id_sportu`)
    REFERENCES `mydb`.`sport` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sport_has_slevovy kod_slevovy kod1`
    FOREIGN KEY (`id_slevoveho_kodu`)
    REFERENCES `mydb`.`slevovy kod` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`slevovy_kod_na_znacky`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`slevovy_kod_na_znacky` ;

CREATE TABLE IF NOT EXISTS `mydb`.`slevovy_kod_na_znacky` (
  `id_znacky` INT NOT NULL,
  `id_slevoveho_kodu` INT NOT NULL,
  PRIMARY KEY (`id_znacky`, `id_slevoveho_kodu`),
  INDEX `fk_znacka_has_slevovy kod_slevovy kod1_idx` (`id_slevoveho_kodu` ASC) VISIBLE,
  INDEX `fk_znacka_has_slevovy kod_znacka1_idx` (`id_znacky` ASC) VISIBLE,
  CONSTRAINT `fk_znacka_has_slevovy kod_znacka1`
    FOREIGN KEY (`id_znacky`)
    REFERENCES `mydb`.`znacka` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_znacka_has_slevovy kod_slevovy kod1`
    FOREIGN KEY (`id_slevoveho_kodu`)
    REFERENCES `mydb`.`slevovy kod` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`material` ;

CREATE TABLE IF NOT EXISTS `mydb`.`material` (
  `id` INT NOT NULL,
  `material` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`materialy_produktu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`materialy_produktu` ;

CREATE TABLE IF NOT EXISTS `mydb`.`materialy_produktu` (
  `id_materialu` INT NOT NULL,
  `id_produktu` INT NOT NULL,
  `procento_materialu` INT NULL,
  PRIMARY KEY (`id_materialu`, `id_produktu`),
  INDEX `fk_material_has_produkt_produkt1_idx` (`id_produktu` ASC) VISIBLE,
  INDEX `fk_material_has_produkt_material1_idx` (`id_materialu` ASC) VISIBLE,
  CONSTRAINT `fk_material_has_produkt_material1`
    FOREIGN KEY (`id_materialu`)
    REFERENCES `mydb`.`material` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_material_has_produkt_produkt1`
    FOREIGN KEY (`id_produktu`)
    REFERENCES `mydb`.`produkt` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`objednavka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`objednavka` ;

CREATE TABLE IF NOT EXISTS `mydb`.`objednavka` (
  `id` INT NOT NULL,
  `id_uzivatele` INT NOT NULL,
  `lokalita_vyzvednuti` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefonni_cislo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `id_uzivatele`),
  INDEX `fk_objednavka_uzivatel1_idx` (`id_uzivatele` ASC) VISIBLE,
  CONSTRAINT `fk_objednavka_uzivatel1`
    FOREIGN KEY (`id_uzivatele`)
    REFERENCES `mydb`.`uzivatel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produkty_v_objednavce`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`produkty_v_objednavce` ;

CREATE TABLE IF NOT EXISTS `mydb`.`produkty_v_objednavce` (
  `id_produktu` INT NOT NULL,
  `id_objednavky` INT NOT NULL,
  `cena_produktu_pri_koupi` INT NULL,
  PRIMARY KEY (`id_produktu`, `id_objednavky`),
  INDEX `fk_produkt_has_objednavka_objednavka1_idx` (`id_objednavky` ASC) VISIBLE,
  INDEX `fk_produkt_has_objednavka_produkt1_idx` (`id_produktu` ASC) VISIBLE,
  CONSTRAINT `fk_produkt_has_objednavka_produkt1`
    FOREIGN KEY (`id_produktu`)
    REFERENCES `mydb`.`produkt` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produkt_has_objednavka_objednavka1`
    FOREIGN KEY (`id_objednavky`)
    REFERENCES `mydb`.`objednavka` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`obrazky_k_produktu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`obrazky_k_produktu` ;

CREATE TABLE IF NOT EXISTS `mydb`.`obrazky_k_produktu` (
  `id_obrazku` INT NOT NULL,
  `id_barvy` INT NOT NULL,
  `id_produktu` INT NOT NULL,
  PRIMARY KEY (`id_obrazku`, `id_barvy`, `id_produktu`),
  INDEX `fk_obrazek_has_barva_barva1_idx` (`id_barvy` ASC) VISIBLE,
  INDEX `fk_obrazek_has_barva_obrazek1_idx` (`id_obrazku` ASC) VISIBLE,
  INDEX `fk_obrazek_has_barva_produkt1_idx` (`id_produktu` ASC) VISIBLE,
  CONSTRAINT `fk_obrazek_has_barva_obrazek1`
    FOREIGN KEY (`id_obrazku`)
    REFERENCES `mydb`.`obrazek` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_obrazek_has_barva_barva1`
    FOREIGN KEY (`id_barvy`)
    REFERENCES `mydb`.`barva` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_obrazek_has_barva_produkt1`
    FOREIGN KEY (`id_produktu`)
    REFERENCES `mydb`.`produkt` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mnozstvi_produktu_urcite_barvy_a_velikosti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`mnozstvi_produktu_urcite_barvy_a_velikosti` ;

CREATE TABLE IF NOT EXISTS `mydb`.`mnozstvi_produktu_urcite_barvy_a_velikosti` (
  `id_barvy` INT NOT NULL,
  `id_produktu` INT NOT NULL,
  `pocet` INT NULL,
  `id_velikosti` INT NOT NULL,
  PRIMARY KEY (`id_barvy`, `id_produktu`, `id_velikosti`),
  INDEX `fk_produkt_has_barva_barva1_idx` (`id_produktu` ASC) VISIBLE,
  INDEX `fk_produkt_has_barva_produkt1_idx` (`id_barvy` ASC) VISIBLE,
  INDEX `fk_mnozstvi_produktu_urcite_barvy_velikost1_idx` (`id_velikosti` ASC) VISIBLE,
  CONSTRAINT `fk_produkt_has_barva_produkt1`
    FOREIGN KEY (`id_barvy`)
    REFERENCES `mydb`.`produkt` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produkt_has_barva_barva1`
    FOREIGN KEY (`id_produktu`)
    REFERENCES `mydb`.`barva` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mnozstvi_produktu_urcite_barvy_velikost1`
    FOREIGN KEY (`id_velikosti`)
    REFERENCES `mydb`.`velikost` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zakoupene_produkty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`zakoupene_produkty` ;

CREATE TABLE IF NOT EXISTS `mydb`.`zakoupene_produkty` (
  `id_uzivatele` INT NOT NULL,
  `id_produktu` INT NOT NULL,
  PRIMARY KEY (`id_uzivatele`, `id_produktu`),
  INDEX `fk_uzivatel_has_produkt_produkt1_idx` (`id_produktu` ASC) VISIBLE,
  INDEX `fk_uzivatel_has_produkt_uzivatel1_idx` (`id_uzivatele` ASC) VISIBLE,
  CONSTRAINT `fk_uzivatel_has_produkt_uzivatel1`
    FOREIGN KEY (`id_uzivatele`)
    REFERENCES `mydb`.`uzivatel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uzivatel_has_produkt_produkt1`
    FOREIGN KEY (`id_produktu`)
    REFERENCES `mydb`.`produkt` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`oblibene_produkty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`oblibene_produkty` ;

CREATE TABLE IF NOT EXISTS `mydb`.`oblibene_produkty` (
  `id_uzivatele` INT NOT NULL,
  `id_produktu` INT NOT NULL,
  PRIMARY KEY (`id_uzivatele`, `id_produktu`),
  INDEX `fk_uzivatel_has_produkt_produkt2_idx` (`id_produktu` ASC) VISIBLE,
  INDEX `fk_uzivatel_has_produkt_uzivatel2_idx` (`id_uzivatele` ASC) VISIBLE,
  CONSTRAINT `fk_uzivatel_has_produkt_uzivatel2`
    FOREIGN KEY (`id_uzivatele`)
    REFERENCES `mydb`.`uzivatel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uzivatel_has_produkt_produkt2`
    FOREIGN KEY (`id_produktu`)
    REFERENCES `mydb`.`produkt` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;